# Generated by Django 4.1.4 on 2023-09-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajexapp', '0002_detail_delete_employees_delete_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
